//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisanKiDukan.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogComment
    {
        public int Id { get; set; }
        public int Blog_Id { get; set; }
        public string CommentAuthor { get; set; }
        public System.DateTime CommentDate { get; set; }
        public bool IsApproved { get; set; }
        public string AuthorEmail { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
