//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisanKiDukan.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class KartDetail
    {
        public int Id { get; set; }
        public int Kart_Id { get; set; }
        public int Product_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Metric_Id { get; set; }
        public bool IsVariant { get; set; }
        public double Volume { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string KartSysIp { get; set; }
    }
}
