
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KisanKiDukan.Models.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class BlogMaster
{

    public int Id { get; set; }

    public string Url { get; set; }

    public string BlogImage { get; set; }

    public string Heading { get; set; }

    public string Short { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

}

}
