//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisanKiDukan.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public int Product_Id { get; set; }
        public int User_Id { get; set; }
        public double Price { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public bool IsDelivered { get; set; }
        public bool IfReturned { get; set; }
        public string ProductName { get; set; }
        public int Order_Id { get; set; }
        public double FinalPrice { get; set; }
        public double DiscountValue { get; set; }
        public double ServiceTax { get; set; }
        public int Quantity { get; set; }
        public string Metrics { get; set; }
        public int Category_Id { get; set; }
        public bool IsCancel { get; set; }
        public int OrderStatus_Id { get; set; }
        public double Volume { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public Nullable<System.DateTime> StatusUpdateDate { get; set; }
        public Nullable<int> VendorId { get; set; }
    }
}
