
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KisanKiDukan.Models.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class Product_Availability
{

    public int Id { get; set; }

    public Nullable<int> Product_Id { get; set; }

    public Nullable<int> Metrics_Id { get; set; }

    public double Price { get; set; }

    public bool IsAvailable { get; set; }

    public Nullable<int> Quantity { get; set; }

    public Nullable<double> OurPrice { get; set; }

    public string Barcode { get; set; }

}

}
