//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisanKiDukan.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string ProductImage { get; set; }
        public Nullable<double> Price { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> Metric_Id { get; set; }
        public bool IsStock { get; set; }
        public Nullable<int> OfferValue { get; set; }
        public Nullable<int> OfferType { get; set; }
        public string Page_Url { get; set; }
        public bool IsReplacement { get; set; }
        public string ReplacementTC { get; set; }
        public Nullable<int> Quantity { get; set; }
        public bool IsFeatured { get; set; }
        public bool IsFreeShipping { get; set; }
        public double ShippingCharge { get; set; }
        public bool IsReviewsAllow { get; set; }
        public string SKU { get; set; }
        public Nullable<int> Brand_Id { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> DiscountCode_Id { get; set; }
        public Nullable<double> OurPrice { get; set; }
        public bool IsVariant { get; set; }
        public string Barcode { get; set; }
        public string HsnCode { get; set; }
        public bool IsRecomend { get; set; }
        public Nullable<double> PremiumAmount { get; set; }
        public Nullable<int> SubId { get; set; }
        public Nullable<bool> IsHotdeals { get; set; }
        public Nullable<bool> IsFeatureProduct { get; set; }
        public Nullable<bool> IsSpecial { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<double> CGST { get; set; }
        public Nullable<double> SGST { get; set; }
        public Nullable<double> IGST { get; set; }
        public Nullable<double> DiscountPrice { get; set; }
        public Nullable<int> AvailPincode { get; set; }
        public List<Product_Image> ProductMultiImages { get; internal set; }
    }
}
