
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KisanKiDukan.Models.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class promotionalbanner
{

    public int Id { get; set; }

    public string promotionalbannerpath { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public string url { get; set; }

    public string productName { get; set; }

    public string Discount { get; set; }

}

}
