//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisanKiDukan.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int Id { get; set; }
        public string VendorName { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNumber { get; set; }
        public string EmailId { get; set; }
        public int LoginMaster_Id { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string CompanyName { get; set; }
        public string Adress { get; set; }
        public string city { get; set; }
        public string Password { get; set; }
        public string LegalCompanyName { get; set; }
        public string BusinessFilingStatus { get; set; }
        public string PAN_No { get; set; }
        public string RegisteredAddress { get; set; }
        public string OperatingAddress { get; set; }
        public string PayToName { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public string IFSC_Code { get; set; }
        public string BranchAddress { get; set; }
        public string PanCard { get; set; }
        public string AddressProof { get; set; }
        public string CancelCheque { get; set; }
        public string SignedDocument { get; set; }
        public string GovtCertificate { get; set; }
        public string FoodLicence { get; set; }
        public string BusinessDocumnet { get; set; }
        public string State { get; set; }
    }
}
